### ISSUE TITLE
Future addition of code/monospace block?

### ISSUE THREAD

**Issue by judah-caruso** [neurosnap/lists.sh#13]
Love the idea and execution of lists, definitely see myself mirroring my main blog on here (especially if gemini support is on the roadmap). I think a good minor addition to the syntax would be some way to create a code/monospace block similar to `<pre/>` in HTML or ``` in markdown. 

I've tried to do it with `>` but that seems to create multiple quote blocks with spacing between lines. If there's already a way to do this or it's out of the scope of the project, please let me know!

Functionally, I think the way gemini defines ``` to *"toggle"* preformatted mode would make for a simple implementation while appealing to people used to both markdown and gemtext syntax.

**Comment by neurosnap** [comment]
gemini is absolutely on the roadmap and I based the lists.sh spec off the idea that it would be easy to translate to gemini.  Also, I was heavily inspired by the gemini formatting spec when devising it.

I like your idea of the toggle preformatted mode.  I'm going to work on this now and see what I can come up with.

Thanks for the suggestion!

**Comment by neurosnap** [comment]
Please see spec for details: https://lists.sh/spec#preformatted
