### ISSUE TITLE
Special format to "break out" of a list

### ISSUE THREAD

**Issue by neurosnap** [neurosnap/lists.sh#21]
Another user submitted feedback that they would like to have a special flag to "break out" of a list.  I fear this does not stay true to the nature of a microblog for lists but I'm open to alternative ideas.

Basically we would provide the ability for the user to close a list.  We already allow something similar with headers.

**Comment by bentsai** [comment]
What are you "breaking into"? In other words, if you're no longer in list mode, are you in paragraphs then? Do you know what that user is trying to accomplish? Why do they propose breaking out?

**Comment by neurosnap** [comment]
Yea I think the idea was to break out into a paragraph.  Basically to have more control over how lists are created.

**Comment by neurosnap** [comment]
I'm going to close this issue because I don't think it stays with the theme of this site.
