### ISSUE TITLE
publish_at variable not working

### ISSUE THREAD

**Issue by silver-dragon** [neurosnap/lists.sh#3]
when I upload a list with 
=: publish_at 2022-03-31
it results in the list having a date of 
Mon January 1, 0001

# Example
Raw:
```
=: publish_at 2022-03-31
Quiet day
Eric worked
Jaime and the kids cleaned and did school
Jaime started her first night shift at her new job.
```
Rendered -> [https://lists.sh/flat-creek-farm/2022-03-31](https://lists.sh/flat-creek-farm/2022-03-31)

**Comment by neurosnap** [comment]
This should be fixed, could you please try uploading the file again?

**Comment by silver-dragon** [comment]
Uploaded again it it looks like its all working now. Cheers!
