### ISSUE TITLE
Markdown rendering?

### ISSUE THREAD

**Issue by ndom91** [neurosnap/lists.sh#30]
What's your opinion on potentially supporting markdown in the "lists" / "posts" files?

I'm a frontend web developer by day, I could definitely help you build it into your frontend :+1:

**Comment by neurosnap** [comment]
Greetings!  I explicitly did not want to support markdown for lists.sh.

I have a GH discussion in this repo that talks about a possible markdown blog platform using the same tech under the hood: https://github.com/neurosnap/lists.sh/discussions/10

Feel free to chat there.
