### ISSUE TITLE
Can page past the end of the discover list a couple of times

### ISSUE THREAD

**Issue by drhayes** [neurosnap/lists.sh#4]
I was digging through the "discover interesting lists" list (heyo) and paged past the end into a couple of blank pages.

This page has a list of lists: https://lists.sh/read?page=8

Hitting next shows a blank page with only `prev` and `next` links. Those probably shouldn't be there if there aren't results to show for the page. I can keep hitting `next` a couple of times and it continues to show blank pages. Eventually I can get to where it only shows `prev`.

As of today, this URL leads to a mostly blank page with `prev` and `next` links: https://lists.sh/read?page=11

This page only has a `prev` but is still blank: https://lists.sh/read?page=12

This link leads to a page with only `prev` as well: https://lists.sh/read?page=10000

Good work, man! I'm super digging the Charm libs and I think this is a great use of them to build a rich, SSH-able experience for techies.

**Comment by neurosnap** [comment]
Hey thanks for reporting this feedback!  I'm going to add this to my shortlist of things to investigate.
